INSERT INTO productos (nombre, precio, create_at) VALUES ('Procesador Intel i7', 300000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Tarjeta Madre ASUS', 150000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('RAM Kingston 16GB', 80000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Disco Duro Seagate 1TB', 50000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Tarjeta de Video Nvidia GTX 1660', 250000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Fuente de Poder Corsair 650W', 70000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Gabinete Cooler Master', 60000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Monitor ASUS 24"', 120000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Teclado Mecánico HyperX', 50000, NOW());
INSERT INTO productos (nombre, precio, create_at) VALUES ('Mouse Logitech G502', 40000, NOW());